export const SET_LOGIN_CREDENTIALS = 'SET_LOGIN_CREDENTIALS';
export const SET_ADMIN_NAV = 'SET_ADMIN_NAV';

export const SET_ADMIN_LISTMESSAGES = 'SET_ADMIN_LISTMESSAGES';

export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';

export const SET_ORDERS_DATA = 'SET_ORDERS_DATA';