export const SET_LOGIN_CREDENTIALS = 'SET_LOGIN_CREDENTIALS';
export const SET_ADMIN_NAV = 'SET_ADMIN_NAV';

export const SET_ADMIN_LISTMESSAGES = 'SET_ADMIN_LISTMESSAGES';

export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';

export const SET_ORDERS_DATA = 'SET_ORDERS_DATA';

export const SET_RIDERS_AV = 'SET_RIDERS_AV';
export const SET_BRANCHES = 'SET_BRANCHES';

export const SET_INCOMING_ORDERS = 'SET_INCOMING_ORDERS';
export const SET_ORDERS_TO_DELIVER = 'SET_ORDERS_TO_DELIVER';
export const SET_TRANSFERRING_BRANCH = 'SET_TRANSFERRING_BRANCH';
export const SET_ONDELIVERY = 'SET_ONDELIVERY';

export const SET_SHIP_IN_UNASSIGNED = 'SET_SHIP_IN_UNASSIGNED';
export const SET_SHIP_OUT_UNASSIGNED = 'SET_SHIP_OUT_UNASSIGNED';

export const SET_SHIP_IN_ASSIGNED = 'SET_SHIP_IN_ASSIGNED';
export const SET_SHIP_OUT_ASSIGNED = 'SET_SHIP_OUT_ASSIGNED';